name: SlicedOptimalTransportSampling

on:
# workflow_dispatch:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: pkg-config
        run: |
          mkdir pkg-config
          cd pkg-config
          bitsadmin.exe /TRANSFER dl http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip           %temp%/pkg-config_0.26-1_win32.zip
          bitsadmin.exe /TRANSFER dl http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip                  %temp%/glib_2.28.8-1_win32.zip
          bitsadmin.exe /TRANSFER dl http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip  %temp%/gettext-runtime_0.18.1.1-2_win32.zip
          powershell Expand-Archive -Path %temp%/pkg-config_0.26-1_win32.zip           -Destination pkg-config
          powershell Expand-Archive -Path %temp%/glib_2.28.8-1_win32.zip               -Destination pkg-config
          powershell Expand-Archive -Path %temp%/gettext-runtime_0.18.1.1-2_win32.zip  -Destination pkg-config
          cur=$(pwd)
          echo ${cur}
          set PATH=%PATH%;${cur}/pkg-config/bin
          echo ${PATH}

      - name: vckpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.sh
          vcpkg integrate install
          vcpkg install ms-gsl
          @REM set PATH=%PATH%;C:/tmp/GSL/include/

      - name: build
        run: |
          git clone https://github.com/loispaulin/Sliced-Optimal-Transport-Sampling sot
          cd sot
          git checkout f315ea9876618e9cf3943a79bc7999b247178e6d
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
          make sot
